@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include DEVICONS/nodejs_small.puml
!include DEVICONS/mongodb.puml
!include FONTAWESOME/users.puml
!include FONTAWESOME/server.puml
!include FONTAWESOME/balance_scale.puml

Person(user, "Customer", "Want to apply operations to images", $sprite="users")

System_Ext(lb, "Load Balancer", $sprite=balance_scale)

System_Boundary(c1, "FrontService") {
    Container(fsapi, "API", "node.js", API to access FrontService, $sprite="nodejs_small")
    ContainerDb(fsdb, "storage", "mongodb cluster", "Stores informations about jobs", $sprite="mongodb")
}
System_Ext(jsapi, "JobService", "API worker.blob.net", "Executes jobs", $sprite="server")
System_Ext(bsapi, "BlobService", "API worker.blob.net", "Stores blobs", $sprite="server")


Rel(user, lb, "Uses", "https")
Rel(lb, fsapi, "Uses", "https")
Rel_R(fsapi, fsdb, "Uses", "mongodb API")
Rel(fsapi, jsapi, "Uses", "REST API")
Rel(fsapi, bsapi, "Uses", "REST API")
Rel_R(jsapi, bsapi, "Uses", "REST API")
@enduml