@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include DEVICONS/nodejs_small.puml
!include FONTAWESOME/users.puml

Person(user, "Customer", "Want to apply operations to images", $sprite="users")

Container(fs, "FrontService", "node.js", "The main interface that the customer interacts with", $sprite="nodejs_small")

Container(api1, "worker.cloud.net", , "Job submissions, job status")
Container(api2, "worker.blob.net", , "Stores blob used by ")


Rel(user, fs, "Uses", "https")
Rel(fs, api1, "Uses", "REST API")
Rel(fs, api2, "Uses", "REST API")
Rel(api1, api2, "Uses", "REST API")
@enduml