@startuml
User -> FrontService: GET /api/v1/job/:id
alt job not yet submitted to JobService or completed
  FrontService -> User: status
else
  alt clientId and tenentId match
    FrontService -> JobService: GET /api/v1/job/:id
    JobService -> FrontService: status
    FrontService -> User: status
  else
  ' User is not owner of job
    FrontService -> User: UnAuthorized
  end
end
@enduml