@startuml
User -> FrontService: POST /api/v1/job

FrontService -> FrontService: Store new object\n- id\n- clientId\n- tenentId\n- status: CREATED
' could store blob too to retry in case blobservice fails

FrontService -> User: - id\n- status: CREATED

FrontService -> BlobService: POST /api/v1/blob
BlobService -> FrontService: Response\n- blobId

FrontService -> FrontService: Update data\n- extBlobId (blobId)\n- status: STORED

FrontService -> JobService: POST /api/v1/job
JobService -> FrontService: Response\n- jobId

FrontService -> FrontService: Update data\n- extJobId (jobId)\n- status: SUBMITTED
@enduml